import { randomBytes } from 'node:crypto';
import { chmod, mkdir, readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { parseEnv } from 'node:util';
import { isLoopbackHostname } from '../server/security.mjs';

function options(argumentsList) {
	const parsed = {};
	for (let index = 0; index < argumentsList.length; index += 2) {
		const key = argumentsList[index];
		const value = argumentsList[index + 1];
		if (!['--origin', '--workspace'].includes(key) || !value || value.startsWith('--')) {
			throw new Error('Usage: npm run setup -- [--origin https://app.example.com] [--workspace /path/to/projects]');
		}
		parsed[key.slice(2)] = value;
	}
	return parsed;
}

function runnerOrigin(value) {
	if (!value) return undefined;
	const url = new URL(value);
	if (url.username || url.password || url.pathname !== '/' || url.search || url.hash) throw new Error('--origin must be an exact origin without credentials, a path, query, or fragment.');
	if (url.protocol !== 'https:' && !(url.protocol === 'http:' && isLoopbackHostname(url.hostname))) throw new Error('--origin must use HTTPS, except for loopback HTTP development.');
	return url.origin;
}

function setValue(source, key, value) {
	const line = `${key}=${JSON.stringify(value)}`;
	const pattern = new RegExp(`^${key}=.*$`, 'm');
	return pattern.test(source) ? source.replace(pattern, line) : `${source}${source && !source.endsWith('\n') ? '\n' : ''}${line}\n`;
}

const setupOptions = options(process.argv.slice(2));
const origin = runnerOrigin(setupOptions.origin);

const environmentFile = resolve('.env');
let current = '';
try { current = await readFile(environmentFile, 'utf8'); }
catch (error) {
	if (error?.code !== 'ENOENT') throw error;
}

const existing = current ? parseEnv(current).TERMINAL_ACCESS_TOKEN?.trim() : undefined;
const token = existing || randomBytes(32).toString('base64url');
let next = current;
if (!existing) {
	next += `${next && !next.endsWith('\n') ? '\n' : ''}# CmdImpact terminal (generated by npm run setup)\n`;
	next = setValue(next, 'TERMINAL_ACCESS_TOKEN', token);
	for (const [key, value] of Object.entries({
		TERMINAL_ALLOWED_ORIGINS: 'http://localhost:4321,http://127.0.0.1:4321,http://localhost:8787,http://127.0.0.1:8787',
		TERMINAL_HOST: '127.0.0.1',
		TERMINAL_PORT: '8787',
		TERMINAL_WORKSPACE: '.data/workspace',
		TERMINAL_STATE_FILE: '.data/sessions.json',
	})) next = setValue(next, key, value);
}
if (origin) {
	next = setValue(next, 'NODE_ENV', origin.startsWith('https://') ? 'production' : 'development');
	next = setValue(next, 'TERMINAL_ALLOWED_ORIGINS', origin);
	next = setValue(next, 'TERMINAL_ALLOW_INSECURE_LOCALHOST', String(origin.startsWith('http://')));
}
if (setupOptions.workspace) next = setValue(next, 'TERMINAL_WORKSPACE', resolve(setupOptions.workspace).replaceAll('\\', '/'));

if (next !== current) {
	await writeFile(environmentFile, next, { mode: 0o600 });
	try { await chmod(environmentFile, 0o600); } catch { /* Windows may not support POSIX modes. */ }
}

await mkdir(resolve(setupOptions.workspace || '.data/workspace'), { recursive: true });

console.log(existing && !origin && !setupOptions.workspace ? 'Terminal configuration already exists in .env.' : 'Terminal configuration is ready in .env.');
console.log(origin ? `Allowed browser dashboard: ${origin}` : 'Open http://localhost:4321/app/');
console.log(`Owner access token: ${token}`);
console.log(`Keep this token private. Run ${origin ? 'npm run server' : 'npm run dev'} to start the runner.`);
