import { randomBytes } from 'node:crypto';
import { chmod, mkdir, readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';

const environmentFile = resolve('.env');
let current = '';
try { current = await readFile(environmentFile, 'utf8'); }
catch (error) {
	if (error?.code !== 'ENOENT') throw error;
}

const existing = current.match(/^TERMINAL_ACCESS_TOKEN=(.+)$/m)?.[1]?.trim();
const token = existing || randomBytes(32).toString('base64url');
if (!existing) {
	const block = [
		'TERMINAL_ACCESS_TOKEN=' + token,
		'TERMINAL_ALLOWED_ORIGINS=http://localhost:4321,http://127.0.0.1:4321,http://localhost:8787,http://127.0.0.1:8787',
		'TERMINAL_HOST=127.0.0.1',
		'TERMINAL_PORT=8787',
		'TERMINAL_WORKSPACE=.data/workspace',
		'TERMINAL_STATE_FILE=.data/sessions.json',
	].join('\n');
	const prefix = current && !current.endsWith('\n') ? `${current}\n` : current;
	await writeFile(environmentFile, `${prefix}${prefix ? '\n' : ''}# CmdImpact terminal (generated by npm run setup)\n${block}\n`, { mode: 0o600 });
	try { await chmod(environmentFile, 0o600); } catch { /* Windows may not support POSIX modes. */ }
}

await mkdir(resolve('.data/workspace'), { recursive: true });

console.log(existing ? 'Terminal configuration already exists in .env.' : 'Created local terminal configuration in .env.');
console.log('Open http://localhost:4321/app/');
console.log(`Owner access token: ${token}`);
console.log('Keep this token private. Run npm run dev for the containerized app.');
